controller_list:
  - name: left_wam_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_wam/base_yaw_joint
      - left_wam/shoulder_pitch_joint
      - left_wam/shoulder_yaw_joint
      - left_wam/elbow_pitch_joint
      - left_wam/wrist_yaw_joint
      - left_wam/wrist_pitch_joint
      - left_wam/palm_yaw_joint

  - name: right_wam_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_wam/base_yaw_joint
      - right_wam/shoulder_pitch_joint
      - right_wam/shoulder_yaw_joint
      - right_wam/elbow_pitch_joint
      - right_wam/wrist_yaw_joint
      - right_wam/wrist_pitch_joint
      - right_wam/palm_yaw_joint
  - name: left_wam_finger_1_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - left_wam/bhand/finger_1/prox_joint
      - left_wam/bhand/finger_1/med_joint
      - left_wam/bhand/finger_1/dist_joint
  - name: left_wam_finger_2_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - left_wam/bhand/finger_2/prox_joint
      - left_wam/bhand/finger_2/med_joint
      - left_wam/bhand/finger_2/dist_joint
  - name: left_wam_finger_3_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - left_wam/bhand/finger_3/med_joint
      - left_wam/bhand/finger_3/dist_joint
  - name: right_wam_finger_1_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - right_wam/bhand/finger_1/prox_joint
      - right_wam/bhand/finger_1/med_joint
      - right_wam/bhand/finger_1/dist_joint
  - name: right_wam_finger_2_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - right_wam/bhand/finger_2/prox_joint
      - right_wam/bhand/finger_2/med_joint
      - right_wam/bhand/finger_2/dist_joint
  - name: right_wam_finger_3_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - right_wam/bhand/finger_3/med_joint
      - right_wam/bhand/finger_3/dist_joint
